version: '2'
services:
  influxdb:
    image: influxdb:0.12
    hostname: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    depends_on:
      - influxdb
      
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    hostname: collector
    links:
      - influxdb
    depends_on:
      - influxdb
